### PR TITLE
159443464 refactor url(s) used to verify logged activities

### PR DESCRIPTION
**Pull request by Chris-Maina**
##### What does this PR do?
Refactors URLs for the services to review, approve, reject logged activities by a society secretary or success ops member
##### Description of Task to be completed?
* Add actions and action creators to reject a logged activity
* Refactor URL to approve logged activities
* Move verify action types and their tests from `societyActivitiesReducer` to  `allActivitiesReducer`
* Add test for the actions to reject an activity

##### What are the relevant Pivotal Tracker stories?
[159443464](https://www.pivotaltracker.com/story/show/159443464)

### CODE REVIEW

**Comment by kimani-ndegwa** [comment]
Please rebase @Chris-Maina

**Comment by Chris-Maina** [comment]
@kimani-ndegwa Done.

**Comment by mkiterian** [comment]
This PR doesn't seem to have any changes

**Comment by Chris-Maina** [comment]
Yes, this is a parent branch to `ch-159326777-refactor-verify-redemption-url` which was merged.

**Comment by kimani-ndegwa** [comment]
Apologies @Chris-Maina . do rebase this once more.

**Pull request closed without merging**
