### PR TITLE
#[156914066] Feature to enable redeeming of society points

### PR DESCRIPTION
**Pull request by Chris-Maina**
#### What does this PR do?
Enables redeeming of society points using the Redeem Points modal.
#### Description of Task to be completed?
Have the following working: 
 - Actions and action creators for redeeming points request, success, and failure.
 - Have a redeem points reducer to handle the actions.
 - Have a form to enable a user to redeem points.
 - A component to display form field errors.
 - A helper function to covert points entered to dollars.
 - Have tests for the redeemPointsReducer, redeemPointsActions, and RedeemPointsForm component.
#### How should this be manually tested?
 `git pull` this branch, `cd` into the project, `yarn install` the dependencies, and `yarn start`. Log into the application and navigate to `Redemptions` page. Click the floating button on the bottom-right corner to have the `Redeem points` modal appear.
#### What are the relevant pivotal tracker stories?
[156914066](https://www.pivotaltracker.com/story/show/156914066)
#### Screenshots (if appropriate)
screen shot 2018-06-06 at 00 15 42
screen shot 2018-06-06 at 00 15 49
screen shot 2018-06-06 at 00 16 11
screen shot 2018-06-06 at 00 16 14

### CODE REVIEW

**Comment by Chris-Maina** [comment]
@kimani-ndegwa Please review this PR.

**Comment by mkiterian** [comment]
Look into the warnings displayed when you run `yarn coverage`

**Comment by mkiterian** [comment]
The spacing between `USD` and the points value should be slightly larger and `USD` is of a slightly smaller font size as per the designs
screen shot 2018-06-06 at 00 51 15

**Comment by Chris-Maina** [comment]
Please review this PR @kimani-ndegwa

**Comment by kimani-ndegwa** [comment]
Across the board request, it seems most of these PR's have coverage issues. Can we make this a priority clean up task for tomorrow morning?

Also ensure that the comments from other devs on the team are looked into before I can merge. @Chris-Maina

**Comment by Chris-Maina** [comment]
Yes, we can @kimani-ndegwa.

**Pull request merged**
