### PR TITLE
Resolves #56137968 - Add VerifyActivities page

### PR DESCRIPTION
**Pull request by john555**
#### Description:
Add verify Activities page. Add ability to switch between pages by clicking links on the sidebar.
Additionally:
- Refactor routing code. All routes are defined in one place.
- Refactor page component code. All pages are wrapped in a `<Page />` component.

#### How to test:
- Checkout to the `ft-create-myactivities-page-156137968` branch.
- Click the VerifyActivities link in the sidebar. The verify activities page should be visible and the title should reflect the change. You should be able to go back to the My Activities page.

### CODE REVIEW

**Comment by joykare** [comment]
Its WIP..? Should it still be reviewed?

**Comment by john555** [comment]
@joykare Yes. It should.

**Comment by mkiterian** [comment]
Looks good

**Comment by andela-ksolomon** [comment]
Looks good to me

**Comment by Farhanisto** [comment]
@john555 whats the reason of changing the name from app.jsx to page.jsx

**Comment by john555** [comment]
@Farhanisto By the old implementation, some routes were defined in `Routes.jsx` and others in `App.jsx`. This isn't good.

All `App.jsx` does is contain a layout for all the pages, hence I renamed it to `Page.jsx`. So, other page components can simply reuse the `<Page />` component.

**Pull request merged**
